name: mautic_api
description: Mautic API Wrapper for Dart and Flutter
version: 1.0.0
homepage: https://github.com/luizeof/dart-mautic-api

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.4
  http: ^0.12.0+4
  meta: ^1.1.8
  convert: ^2.1.1
